name: Daily Trading Bot Analysis

on:
  schedule:
    - cron: '0 9 * * 1-5'  # ירוץ כל יום עסקים ב-9:00 בבוקר (UTC)
  workflow_dispatch:  # מאפשר הרצה ידנית

env:
  NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
  ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create default tickers file
      run: |
        echo '{
          "tickers": [
            "AAPL", "MSFT", "GOOGL", "AMZN", "META",
            "TSLA", "NVDA", "JPM", "V", "JNJ"
          ]
        }' > tickers.json

    - name: Run trading bot
      run: |
        python main.py

    - name: Upload results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: trading-results
        path: |
          trading_signals.json
          trading_signals.html
          trading_bot.log

    - name: Send Telegram notification
      if: always()
      run: |
        if [ -f trading_signals.json ]; then
          SIGNALS=$(python -c "
          import json
          with open('trading_signals.json') as f:
              data = json.load(f)
          print(data['signals_generated'])
          ")
          
          if [ "$SIGNALS" -gt 0 ]; then
            TOP_SIGNAL=$(python -c "
            import json
            with open('trading_signals.json') as f:
                data = json.load(f)
            if data['signals']:
                signal = data['signals'][0]
                print(f'{signal[\"ticker\"]}: {signal[\"action\"]} at ${signal[\"price\"]:.2f}')
            ")
            
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
              -d chat_id="$TELEGRAM_CHAT_ID" \
              -d text="🤖 Trading Bot Complete - Generated $SIGNALS signals. Top: $TOP_SIGNAL"
          else
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
              -d chat_id="$TELEGRAM_CHAT_ID" \
              -d text="🤖 Trading Bot Complete - No signals generated today."
          fi
        else
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="❌ Trading Bot Failed - Error running bot"
        fi
