name: Run Trading Bot

on:
  schedule:
    - cron: '30 */2 * * *'  # Every 2 hours, every day
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy yfinance requests scikit-learn matplotlib xgboost
          python -c "import xgboost; print('xgboost installed:', xgboost.__version__)"
        continue-on-error: false

      - name: Run trading bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python trading_bot.py
        timeout-minutes: 10

      - name: Notify on failure
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d text="*Trading Bot Failed*\nRun failed or timed out after 10 minutes. Check GitHub Actions logs." \
          -d parse_mode=Markdown

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trading-bot-output
          path: |
            *.csv
            *.png
            *.pkl
            trading_bot.log
